// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function AskAgent(arg1:string,arg2:string,arg3:string):Promise<wails.Result_meet_sieve_internal_transport_wails_AgentAskDTO_>;

export function GetAgentRecoveryCommands(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_AgentRecoveryCommandsDTO_>;

export function GetAgentSettings():Promise<wails.Result_meet_sieve_internal_transport_wails_AgentSettingsDTO_>;

export function GetAgentState(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_AgentStateDTO_>;

export function GetAgentTimeline(arg1:string,arg2:number,arg3:number):Promise<wails.Result___meet_sieve_internal_transport_wails_AgentTimelineEntryDTO_>;

export function InterruptAgent(arg1:string,arg2:string):Promise<wails.Result_bool_>;

export function ProbeAgent():Promise<wails.Result_meet_sieve_internal_transport_wails_AgentAvailabilityDTO_>;

export function RespondAgentApproval(arg1:string,arg2:string,arg3:string,arg4:string):Promise<wails.Result_bool_>;

export function RetryAgent(arg1:string):Promise<wails.Result_bool_>;

export function SaveAgentSettings(arg1:wails.SaveAgentSettingsDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_AgentSettingsDTO_>;

export function StartWakeWordTest():Promise<wails.Result_meet_sieve_internal_transport_wails_WakeWordTestStateDTO_>;

export function StopWakeWordTest():Promise<wails.Result_meet_sieve_internal_transport_wails_WakeWordTestStateDTO_>;
