// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskAgent(arg1, arg2, arg3) {
  return window['go']['wails']['AgentBinding']['AskAgent'](arg1, arg2, arg3);
}

export function GetAgentRecoveryCommands(arg1) {
  return window['go']['wails']['AgentBinding']['GetAgentRecoveryCommands'](arg1);
}

export function GetAgentSettings() {
  return window['go']['wails']['AgentBinding']['GetAgentSettings']();
}

export function GetAgentState(arg1) {
  return window['go']['wails']['AgentBinding']['GetAgentState'](arg1);
}

export function GetAgentTimeline(arg1, arg2, arg3) {
  return window['go']['wails']['AgentBinding']['GetAgentTimeline'](arg1, arg2, arg3);
}

export function InterruptAgent(arg1, arg2) {
  return window['go']['wails']['AgentBinding']['InterruptAgent'](arg1, arg2);
}

export function ProbeAgent() {
  return window['go']['wails']['AgentBinding']['ProbeAgent']();
}

export function RespondAgentApproval(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['AgentBinding']['RespondAgentApproval'](arg1, arg2, arg3, arg4);
}

export function RetryAgent(arg1) {
  return window['go']['wails']['AgentBinding']['RetryAgent'](arg1);
}

export function SaveAgentSettings(arg1) {
  return window['go']['wails']['AgentBinding']['SaveAgentSettings'](arg1);
}

export function StartWakeWordTest() {
  return window['go']['wails']['AgentBinding']['StartWakeWordTest']();
}

export function StopWakeWordTest() {
  return window['go']['wails']['AgentBinding']['StopWakeWordTest']();
}
