// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetASRSettings() {
  return window['go']['wails']['ASRBinding']['GetASRSettings']();
}

export function GetASRTimeline(arg1, arg2, arg3) {
  return window['go']['wails']['ASRBinding']['GetASRTimeline'](arg1, arg2, arg3);
}

export function GetRawRecordState(arg1) {
  return window['go']['wails']['ASRBinding']['GetRawRecordState'](arg1);
}

export function RetryRealtimeASR(arg1) {
  return window['go']['wails']['ASRBinding']['RetryRealtimeASR'](arg1);
}

export function SaveASRSettings(arg1) {
  return window['go']['wails']['ASRBinding']['SaveASRSettings'](arg1);
}

export function TestASRConnection(arg1) {
  return window['go']['wails']['ASRBinding']['TestASRConnection'](arg1);
}
