// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetASRSettings():Promise<wails.Result_meet_sieve_internal_transport_wails_ASRSettingsDTO_>;

export function GetASRTimeline(arg1:string,arg2:number,arg3:number):Promise<wails.Result___meet_sieve_internal_transport_wails_ASRTimelineEntryDTO_>;

export function GetRawRecordState(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_RawRecordStateDTO_>;

export function RetryRealtimeASR(arg1:string):Promise<wails.Result_bool_>;

export function SaveASRSettings(arg1:wails.SaveASRSettingsDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_ASRSettingsDTO_>;

export function TestASRConnection(arg1:wails.TestASRConnectionDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_ASRConnectionProbeDTO_>;
