// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAudioSettings() {
  return window['go']['wails']['AudioSettingsBinding']['GetAudioSettings']();
}

export function SaveAudioSettings(arg1) {
  return window['go']['wails']['AudioSettingsBinding']['SaveAudioSettings'](arg1);
}

export function TestAudioDevice(arg1) {
  return window['go']['wails']['AudioSettingsBinding']['TestAudioDevice'](arg1);
}
