// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetAudioSettings():Promise<wails.Result_meet_sieve_internal_transport_wails_AudioSettingsDTO_>;

export function SaveAudioSettings(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_AudioSettingsDTO_>;

export function TestAudioDevice(arg1:string):Promise<wails.Result_bool_>;
