// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBootstrapState() {
  return window['go']['wails']['BootstrapBinding']['GetBootstrapState']();
}

export function RetryDatabaseUpgrade() {
  return window['go']['wails']['BootstrapBinding']['RetryDatabaseUpgrade']();
}

export function UseWorkspace(arg1) {
  return window['go']['wails']['BootstrapBinding']['UseWorkspace'](arg1);
}
