// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetBootstrapState():Promise<wails.Result_meet_sieve_internal_transport_wails_BootstrapStateDTO_>;

export function RetryDatabaseUpgrade():Promise<wails.Result_meet_sieve_internal_transport_wails_BootstrapStateDTO_>;

export function UseWorkspace(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_BootstrapStateDTO_>;
