// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChooseAndSendMeetingAttachment(arg1) {
  return window['go']['wails']['ContentBinding']['ChooseAndSendMeetingAttachment'](arg1);
}

export function GetLiveMeetingStatus(arg1) {
  return window['go']['wails']['ContentBinding']['GetLiveMeetingStatus'](arg1);
}

export function GetMeetingTimeline(arg1) {
  return window['go']['wails']['ContentBinding']['GetMeetingTimeline'](arg1);
}

export function SendMeetingMessage(arg1) {
  return window['go']['wails']['ContentBinding']['SendMeetingMessage'](arg1);
}
