// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function ChooseAndSendMeetingAttachment(arg1:wails.ChooseAttachmentDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_AttachmentSendDTO_>;

export function GetLiveMeetingStatus(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_LiveMeetingStatusDTO_>;

export function GetMeetingTimeline(arg1:wails.TimelineQueryDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_TimelinePageDTO_>;

export function SendMeetingMessage(arg1:wails.SendMeetingMessageDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_TimelineEntryDTO_>;
