// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddUtteranceToVoiceSamples(arg1) {
  return window['go']['wails']['CorrectionBinding']['AddUtteranceToVoiceSamples'](arg1);
}

export function CorrectResourceDescription(arg1) {
  return window['go']['wails']['CorrectionBinding']['CorrectResourceDescription'](arg1);
}

export function CorrectSpeakerCluster(arg1) {
  return window['go']['wails']['CorrectionBinding']['CorrectSpeakerCluster'](arg1);
}

export function CorrectUtteranceSpeaker(arg1) {
  return window['go']['wails']['CorrectionBinding']['CorrectUtteranceSpeaker'](arg1);
}

export function CorrectUtteranceText(arg1) {
  return window['go']['wails']['CorrectionBinding']['CorrectUtteranceText'](arg1);
}

export function CreateUtteranceAudioClip(arg1) {
  return window['go']['wails']['CorrectionBinding']['CreateUtteranceAudioClip'](arg1);
}

export function GetCorrectionEntry(arg1) {
  return window['go']['wails']['CorrectionBinding']['GetCorrectionEntry'](arg1);
}

export function GetSpeakerStatus(arg1) {
  return window['go']['wails']['CorrectionBinding']['GetSpeakerStatus'](arg1);
}

export function ListCorrectionEntries(arg1, arg2, arg3) {
  return window['go']['wails']['CorrectionBinding']['ListCorrectionEntries'](arg1, arg2, arg3);
}

export function RetryRawRecordProjection(arg1) {
  return window['go']['wails']['CorrectionBinding']['RetryRawRecordProjection'](arg1);
}

export function RetrySpeakerProcessing(arg1) {
  return window['go']['wails']['CorrectionBinding']['RetrySpeakerProcessing'](arg1);
}

export function RevokeAudioClip(arg1) {
  return window['go']['wails']['CorrectionBinding']['RevokeAudioClip'](arg1);
}
