// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function AddUtteranceToVoiceSamples(arg1:wails.MeetingClipDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_VoiceSampleChangedDTO_>;

export function CorrectResourceDescription(arg1:wails.ResourceCorrectionDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_CorrectionResultDTO_>;

export function CorrectSpeakerCluster(arg1:wails.ClusterCorrectionDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_CorrectionResultDTO_>;

export function CorrectUtteranceSpeaker(arg1:wails.CorrectionCommandDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_CorrectionResultDTO_>;

export function CorrectUtteranceText(arg1:wails.CorrectionCommandDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_CorrectionResultDTO_>;

export function CreateUtteranceAudioClip(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_AudioClipDTO_>;

export function GetCorrectionEntry(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_CorrectionEntryDTO_>;

export function GetSpeakerStatus(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_SpeakerStatusDTO_>;

export function ListCorrectionEntries(arg1:string,arg2:number,arg3:number):Promise<wails.Result_meet_sieve_internal_transport_wails_CorrectionPageDTO_>;

export function RetryRawRecordProjection(arg1:string):Promise<wails.Result_bool_>;

export function RetrySpeakerProcessing(arg1:string):Promise<wails.Result_bool_>;

export function RevokeAudioClip(arg1:string):Promise<wails.Result_bool_>;
