// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function DeleteMeeting(arg1:wails.DeleteMeetingDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_DeletionJobDTO_>;

export function GetDeletionJob(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_DeletionJobDTO_>;

export function PreviewMeetingDeletion(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_DeletionPreviewDTO_>;

export function RetryDeletion(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_DeletionJobDTO_>;
