// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportGlobalDiagnostic() {
  return window['go']['wails']['DiagnosticBinding']['ExportGlobalDiagnostic']();
}

export function ExportMeetingDiagnostic(arg1) {
  return window['go']['wails']['DiagnosticBinding']['ExportMeetingDiagnostic'](arg1);
}

export function GetStorageScan() {
  return window['go']['wails']['DiagnosticBinding']['GetStorageScan']();
}

export function OpenLogDirectory() {
  return window['go']['wails']['DiagnosticBinding']['OpenLogDirectory']();
}

export function StartStorageScan() {
  return window['go']['wails']['DiagnosticBinding']['StartStorageScan']();
}
