// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function ExportGlobalDiagnostic():Promise<wails.Result_meet_sieve_internal_transport_wails_DiagnosticExportDTO_>;

export function ExportMeetingDiagnostic(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_DiagnosticExportDTO_>;

export function GetStorageScan():Promise<wails.Result_meet_sieve_internal_transport_wails_StorageScanDTO_>;

export function OpenLogDirectory():Promise<wails.Result_meet_sieve_internal_transport_wails_CommandResultDTO_>;

export function StartStorageScan():Promise<wails.Result_meet_sieve_internal_transport_wails_StorageScanDTO_>;
