// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFinalizationState(arg1) {
  return window['go']['wails']['FinalizationBinding']['GetFinalizationState'](arg1);
}

export function RetryAgentFinalSync(arg1, arg2) {
  return window['go']['wails']['FinalizationBinding']['RetryAgentFinalSync'](arg1, arg2);
}

export function RetryFinalization(arg1) {
  return window['go']['wails']['FinalizationBinding']['RetryFinalization'](arg1);
}
