// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetFinalizationState(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_FinalizationStateDTO_>;

export function RetryAgentFinalSync(arg1:string,arg2:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MeetingStateEventDTO_>;

export function RetryFinalization(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_FinalizationStateDTO_>;
