// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGapConflict(arg1, arg2) {
  return window['go']['wails']['GapBinding']['GetGapConflict'](arg1, arg2);
}

export function GetGapState(arg1) {
  return window['go']['wails']['GapBinding']['GetGapState'](arg1);
}

export function ResolveGapConflict(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['wails']['GapBinding']['ResolveGapConflict'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function RetryGapCompensation(arg1, arg2, arg3) {
  return window['go']['wails']['GapBinding']['RetryGapCompensation'](arg1, arg2, arg3);
}

export function StartGapCompensation(arg1, arg2) {
  return window['go']['wails']['GapBinding']['StartGapCompensation'](arg1, arg2);
}

export function StopGapCompensation(arg1, arg2) {
  return window['go']['wails']['GapBinding']['StopGapCompensation'](arg1, arg2);
}
