// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetGapConflict(arg1:string,arg2:string):Promise<wails.Result_meet_sieve_internal_transport_wails_GapConflictDTO_>;

export function GetGapState(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_GapStateDTO_>;

export function ResolveGapConflict(arg1:string,arg2:string,arg3:number,arg4:string,arg5:Array<wails.GapResolutionEditDTO>,arg6:string):Promise<wails.Result_meet_sieve_internal_transport_wails_GapStateDTO_>;

export function RetryGapCompensation(arg1:string,arg2:Array<string>,arg3:string):Promise<wails.Result_meet_sieve_internal_transport_wails_GapCommandDTO_>;

export function StartGapCompensation(arg1:string,arg2:string):Promise<wails.Result_meet_sieve_internal_transport_wails_GapCommandDTO_>;

export function StopGapCompensation(arg1:string,arg2:string):Promise<wails.Result_meet_sieve_internal_transport_wails_GapCommandDTO_>;
