// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelGuestUpload(arg1) {
  return window['go']['wails']['LANBinding']['CancelGuestUpload'](arg1);
}

export function GetLANStatus() {
  return window['go']['wails']['LANBinding']['GetLANStatus']();
}

export function ListLANInterfaces() {
  return window['go']['wails']['LANBinding']['ListLANInterfaces']();
}

export function RetryLAN(arg1) {
  return window['go']['wails']['LANBinding']['RetryLAN'](arg1);
}

export function StopLAN() {
  return window['go']['wails']['LANBinding']['StopLAN']();
}
