// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CancelGuestUpload(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_CancelUploadDTO_>;

export function GetLANStatus():Promise<wails.Result_meet_sieve_internal_transport_wails_LANStatusDTO_>;

export function ListLANInterfaces():Promise<wails.Result_meet_sieve_internal_transport_wails_LANInterfaceListDTO_>;

export function RetryLAN(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_LANStatusDTO_>;

export function StopLAN():Promise<wails.Result_meet_sieve_internal_transport_wails_LANStatusDTO_>;
