// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EndMeeting(arg1) {
  return window['go']['wails']['MeetingBinding']['EndMeeting'](arg1);
}

export function GetActiveMeeting() {
  return window['go']['wails']['MeetingBinding']['GetActiveMeeting']();
}

export function GetCreateDraft() {
  return window['go']['wails']['MeetingBinding']['GetCreateDraft']();
}

export function GetLatestInterruptedMeeting() {
  return window['go']['wails']['MeetingBinding']['GetLatestInterruptedMeeting']();
}

export function RetryMeetingRecovery(arg1) {
  return window['go']['wails']['MeetingBinding']['RetryMeetingRecovery'](arg1);
}

export function StartMeeting(arg1) {
  return window['go']['wails']['MeetingBinding']['StartMeeting'](arg1);
}
