// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function EndMeeting(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MeetingProjectionDTO_>;

export function GetActiveMeeting():Promise<wails.Result_meet_sieve_internal_transport_wails_ActiveMeetingDTO_>;

export function GetCreateDraft():Promise<wails.Result_meet_sieve_internal_transport_wails_MeetingCreateDraftDTO_>;

export function GetLatestInterruptedMeeting():Promise<wails.Result_meet_sieve_internal_transport_wails_ActiveMeetingDTO_>;

export function RetryMeetingRecovery(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MeetingProjectionDTO_>;

export function StartMeeting(arg1:wails.StartMeetingDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_MeetingProjectionDTO_>;
