// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmMinute(arg1, arg2, arg3) {
  return window['go']['wails']['MinutesBinding']['ConfirmMinute'](arg1, arg2, arg3);
}

export function GenerateMinutes(arg1, arg2, arg3) {
  return window['go']['wails']['MinutesBinding']['GenerateMinutes'](arg1, arg2, arg3);
}

export function GetMinutesSettings() {
  return window['go']['wails']['MinutesBinding']['GetMinutesSettings']();
}

export function GetMinutesState(arg1) {
  return window['go']['wails']['MinutesBinding']['GetMinutesState'](arg1);
}

export function ListMinuteVersions(arg1, arg2, arg3) {
  return window['go']['wails']['MinutesBinding']['ListMinuteVersions'](arg1, arg2, arg3);
}

export function RestoreMinuteVersion(arg1, arg2, arg3) {
  return window['go']['wails']['MinutesBinding']['RestoreMinuteVersion'](arg1, arg2, arg3);
}

export function SaveMinuteDraft(arg1, arg2, arg3, arg4) {
  return window['go']['wails']['MinutesBinding']['SaveMinuteDraft'](arg1, arg2, arg3, arg4);
}

export function SaveMinutesSettings(arg1) {
  return window['go']['wails']['MinutesBinding']['SaveMinutesSettings'](arg1);
}

export function StopMinutesGeneration(arg1, arg2) {
  return window['go']['wails']['MinutesBinding']['StopMinutesGeneration'](arg1, arg2);
}
