// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function ConfirmMinute(arg1:string,arg2:string,arg3:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MinutesStateDTO_>;

export function GenerateMinutes(arg1:string,arg2:boolean,arg3:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MinuteMutationDTO_>;

export function GetMinutesState(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MinutesStateDTO_>;

export function ListMinuteVersions(arg1:string,arg2:number,arg3:number):Promise<wails.Result_meet_sieve_internal_transport_wails_MinuteVersionPageDTO_>;

export function RestoreMinuteVersion(arg1:string,arg2:string,arg3:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MinuteMutationDTO_>;

export function SaveMinuteDraft(arg1:string,arg2:string,arg3:string,arg4:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MinuteMutationDTO_>;

export function StopMinutesGeneration(arg1:string,arg2:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MeetingStateEventDTO_>;
