// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CreateGroup(arg1:wails.CreateGroupDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_GroupDTO_>;

export function CreateMember(arg1:wails.CreateMemberDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_MemberDTO_>;

export function DeleteAllMemberVoiceSamples(arg1:string):Promise<wails.Result_bool_>;

export function DeleteGroup(arg1:string):Promise<wails.Result_bool_>;

export function DeleteMember(arg1:string):Promise<wails.Result_bool_>;

export function GetGroup(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_GroupDTO_>;

export function GetMeetingPeopleOptions():Promise<wails.Result_meet_sieve_internal_transport_wails_MeetingPeopleOptionsDTO_>;

export function GetMember(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MemberDTO_>;

export function GetMemberDetail(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MemberDetailDTO_>;

export function ListGroups():Promise<wails.Result___meet_sieve_internal_transport_wails_GroupDTO_>;

export function ListMembers():Promise<wails.Result___meet_sieve_internal_transport_wails_MemberDTO_>;

export function UpdateGroup(arg1:string,arg2:wails.UpdateGroupDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_GroupDTO_>;

export function UpdateMember(arg1:string,arg2:wails.UpdateMemberDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_MemberDTO_>;
