// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveMember(arg1) {
  return window['go']['wails']['PeopleBinding']['ArchiveMember'](arg1)
}

export function CreateGroup(arg1) {
  return window['go']['wails']['PeopleBinding']['CreateGroup'](arg1)
}

export function CreateMember(arg1) {
  return window['go']['wails']['PeopleBinding']['CreateMember'](arg1)
}

export function DeleteGroup(arg1) {
  return window['go']['wails']['PeopleBinding']['DeleteGroup'](arg1)
}

export function DeleteMember(arg1) {
  return window['go']['wails']['PeopleBinding']['DeleteMember'](arg1)
}

export function GetGroup(arg1) {
  return window['go']['wails']['PeopleBinding']['GetGroup'](arg1)
}

export function GetMeetingPeopleOptions() {
  return window['go']['wails']['PeopleBinding']['GetMeetingPeopleOptions']()
}

export function GetMember(arg1) {
  return window['go']['wails']['PeopleBinding']['GetMember'](arg1)
}

export function ListGroups() {
  return window['go']['wails']['PeopleBinding']['ListGroups']()
}

export function ListMembers() {
  return window['go']['wails']['PeopleBinding']['ListMembers']()
}

export function UpdateGroup(arg1, arg2) {
  return window['go']['wails']['PeopleBinding']['UpdateGroup'](arg1, arg2)
}

export function UpdateMember(arg1, arg2) {
  return window['go']['wails']['PeopleBinding']['UpdateMember'](arg1, arg2)
}
