// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHome() {
  return window['go']['wails']['QueryBinding']['GetHome']();
}

export function GetInterruptedRecovery(arg1) {
  return window['go']['wails']['QueryBinding']['GetInterruptedRecovery'](arg1);
}

export function GetMeetingDetail(arg1) {
  return window['go']['wails']['QueryBinding']['GetMeetingDetail'](arg1);
}

export function ListMeetingContent(arg1) {
  return window['go']['wails']['QueryBinding']['ListMeetingContent'](arg1);
}

export function ListMeetings(arg1) {
  return window['go']['wails']['QueryBinding']['ListMeetings'](arg1);
}

export function ListTranscript(arg1) {
  return window['go']['wails']['QueryBinding']['ListTranscript'](arg1);
}
