// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetHome():Promise<wails.Result_meet_sieve_internal_transport_wails_HomeDTO_>;

export function GetInterruptedRecovery(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_InterruptedRecoveryDTO_>;

export function GetMeetingDetail(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_MeetingDetailDTO_>;

export function ListMeetingContent(arg1:wails.SeqPageInputDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_ContentPageDTO_>;

export function ListMeetings(arg1:wails.MeetingListInputDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_MeetingPageDTO_>;

export function ListTranscript(arg1:wails.SeqPageInputDTO):Promise<wails.Result_meet_sieve_internal_transport_wails_TranscriptPageDTO_>;
