// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenExternalLink(arg1) {
  return window['go']['wails']['ResourceBinding']['OpenExternalLink'](arg1);
}

export function OpenResource(arg1) {
  return window['go']['wails']['ResourceBinding']['OpenResource'](arg1);
}

export function RevealResource(arg1) {
  return window['go']['wails']['ResourceBinding']['RevealResource'](arg1);
}
