// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function OpenExternalLink(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_ResourceOpenDTO_>;

export function OpenResource(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_ResourceOpenDTO_>;

export function RevealResource(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_ResourceOpenDTO_>;
