// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBuildInfo() {
  return window['go']['wails']['SystemBinding']['GetBuildInfo']();
}

export function GetHealth() {
  return window['go']['wails']['SystemBinding']['GetHealth']();
}

export function RunEventRoundTrip(arg1) {
  return window['go']['wails']['SystemBinding']['RunEventRoundTrip'](arg1);
}
