// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetBuildInfo():Promise<wails.Result_meet_sieve_internal_app_buildinfo_Info_>;

export function GetHealth():Promise<wails.Result_meet_sieve_internal_app_health_Snapshot_>;

export function RunEventRoundTrip(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_AppEvent_string__>;
