// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadOfficialVoiceModel() {
  return window['go']['wails']['VoiceModelBinding']['DownloadOfficialVoiceModel']();
}

export function GetVoiceModelState() {
  return window['go']['wails']['VoiceModelBinding']['GetVoiceModelState']();
}

export function ImportOfflineVoiceModel() {
  return window['go']['wails']['VoiceModelBinding']['ImportOfflineVoiceModel']();
}

export function SetAfterActivate(arg1) {
  return window['go']['wails']['VoiceModelBinding']['SetAfterActivate'](arg1);
}
