// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function CancelVoiceRecording():Promise<wails.Result_bool_>;

export function ChooseVoiceSample():Promise<wails.Result_meet_sieve_internal_transport_wails_VoiceFileSelectionDTO_>;

export function DeleteAllVoiceSamples(arg1:string):Promise<wails.Result_bool_>;

export function DeleteVoiceSample(arg1:string,arg2:string):Promise<wails.Result_bool_>;

export function GetVoiceRecordingState():Promise<wails.Result_meet_sieve_internal_transport_wails_VoiceRecordingStateDTO_>;

export function ListInputDevices():Promise<wails.Result___meet_sieve_internal_transport_wails_InputDeviceDTO_>;

export function ListVoiceSamples(arg1:string):Promise<wails.Result___meet_sieve_internal_transport_wails_VoiceSampleDTO_>;

export function ProcessVoiceSample(arg1:string,arg2:string,arg3:string):Promise<wails.Result_meet_sieve_internal_transport_wails_VoiceSampleDTO_>;

export function RebuildVoiceEmbeddings():Promise<wails.Result_meet_sieve_internal_service_voice_RebuildProgress_>;

export function StartVoiceRecording(arg1:string,arg2:string,arg3:string):Promise<wails.Result_bool_>;

export function StopVoiceRecording():Promise<wails.Result_meet_sieve_internal_transport_wails_VoiceSampleDTO_>;
