// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function DownloadOfficialVoiceModel():Promise<wails.Result_meet_sieve_internal_transport_wails_VoiceModelDTO_>;

export function GetVoiceModelState():Promise<wails.Result_meet_sieve_internal_transport_wails_VoiceModelDTO_>;

export function ImportOfflineVoiceModel():Promise<wails.Result_meet_sieve_internal_transport_wails_VoiceModelDTO_>;

export function SetAfterActivate(arg1:any):Promise<void>;
