// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelVoiceRecording() {
  return window['go']['wails']['VoiceBinding']['CancelVoiceRecording']();
}

export function ChooseVoiceSample() {
  return window['go']['wails']['VoiceBinding']['ChooseVoiceSample']();
}

export function DeleteAllVoiceSamples(arg1) {
  return window['go']['wails']['VoiceBinding']['DeleteAllVoiceSamples'](arg1);
}

export function DeleteVoiceSample(arg1, arg2) {
  return window['go']['wails']['VoiceBinding']['DeleteVoiceSample'](arg1, arg2);
}

export function GetVoiceRecordingState() {
  return window['go']['wails']['VoiceBinding']['GetVoiceRecordingState']();
}

export function ListInputDevices() {
  return window['go']['wails']['VoiceBinding']['ListInputDevices']();
}

export function ListVoiceSamples(arg1) {
  return window['go']['wails']['VoiceBinding']['ListVoiceSamples'](arg1);
}

export function ProcessVoiceSample(arg1, arg2, arg3) {
  return window['go']['wails']['VoiceBinding']['ProcessVoiceSample'](arg1, arg2, arg3);
}

export function RebuildVoiceEmbeddings() {
  return window['go']['wails']['VoiceBinding']['RebuildVoiceEmbeddings']();
}

export function StartVoiceRecording(arg1, arg2, arg3) {
  return window['go']['wails']['VoiceBinding']['StartVoiceRecording'](arg1, arg2, arg3);
}

export function StopVoiceRecording() {
  return window['go']['wails']['VoiceBinding']['StopVoiceRecording']();
}
