// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetWorkspaceSettings() {
  return window['go']['wails']['WorkspaceBinding']['GetWorkspaceSettings']();
}

export function InspectWorkspaceCandidate(arg1) {
  return window['go']['wails']['WorkspaceBinding']['InspectWorkspaceCandidate'](arg1);
}

export function SaveWorkspacePath(arg1) {
  return window['go']['wails']['WorkspaceBinding']['SaveWorkspacePath'](arg1);
}
