// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wails} from '../models';

export function GetWorkspaceSettings():Promise<wails.Result_meet_sieve_internal_transport_wails_WorkspaceSettingsDTO_>;

export function InspectWorkspaceCandidate(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_WorkspaceCandidateDTO_>;

export function SaveWorkspacePath(arg1:string):Promise<wails.Result_meet_sieve_internal_transport_wails_WorkspaceSettingsDTO_>;
